language: go

dist: focal

# Remove this if using external Travis
group: focal

go:
- 1.20.x
- 1.21.x
- 1.22.x

notifications:
  email: true

env:
  global:
    - GO111MODULE=on

before_install:
  - pyenv global 3.8

install:
  - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.60.3

script:
  - make travis-ci

# To enable semantic-release, uncomment these sections.
# before_deploy:
#   - nvm install 18
#   - node --version
#   - npm --version
#   - npm install
#   - pip install --user bump-my-version
#
# deploy:
#   - provider: script
#     script: npm run semantic-release
#     skip_cleanup: true
#     on:
#       go: '1.20.x'
#       branch: main
