language: go
dist: focal

go: 
  - 1.19.x

notifications:
  email: true

env:
  global:
    - GO111MODULE=on

before_install:
  - sudo apt-get update
  - sudo apt-get install python
  - nvm install 14
  - npm install -g npm@9.x

install:
  - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.53.3

script:
  - make travis-ci

